# Generated by Django 5.0 on 2023-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_jobs',
            name='title',
            field=models.CharField(default=2, max_length=350),
            preserve_default=False,
        ),
    ]
