# Generated by Django 5.0 on 2023-12-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_add_jobs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_jobs',
            name='link',
        ),
    ]
