# Generated by Django 5.0 on 2023-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_popular_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('link_skype', models.CharField(max_length=350)),
                ('link_facebook', models.CharField(max_length=350)),
                ('link_linkedin', models.CharField(max_length=350)),
                ('name', models.CharField(max_length=350)),
                ('profession', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
