# Generated by Django 5.0 on 2023-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_course',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
