# Generated by Django 5.0 on 2024-01-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_jobs',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
