# Generated by Django 5.0 on 2023-12-18 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskusers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
            preserve_default=False,
        ),
    ]
