# Generated by Django 5.0 on 2023-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_taskusers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_task',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
