# Generated by Django 5.0.6 on 2024-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField()),
                ('holiday', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('day', models.IntegerField()),
                ('temp_inside', models.FloatField()),
                ('temp_outside', models.FloatField()),
                ('temp_dif', models.FloatField()),
            ],
        ),
    ]
