# Generated by Django 5.0.6 on 2024-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtemperature',
            name='temp_dif',
            field=models.FloatField(editable=False),
        ),
    ]
