# Generated by Django 4.2.7 on 2023-11-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Add jobs',
            },
        ),
    ]
