# Generated by Django 4.2.7 on 2023-11-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_jobs',
            name='description',
        ),
    ]
