# Generated by Django 4.2.7 on 2023-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_add_jobs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('link', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='add_jobs',
            name='link',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='add_jobs',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
