# Generated by Django 4.2.7 on 2023-11-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_image_alter_add_jobs_link_alter_add_jobs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
    ]
