# Generated by Django 5.0.1 on 2024-01-21 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_max',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('product_name', models.CharField(max_length=350, null=True, verbose_name='Mahsulotning nomi')),
                ('description', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('company', models.CharField(blank=True, max_length=350, verbose_name='Mahsulotning kompaniyasi')),
                ('mahsulot', models.CharField(blank=True, max_length=350, verbose_name='Kompniyaning mahsuloti')),
                ('olchov', models.CharField(blank=True, max_length=350, verbose_name='Olchovi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('material', models.CharField(blank=True, max_length=350, verbose_name='Material')),
                ('status', models.CharField(blank=True, max_length=350, verbose_name='Holati')),
                ('kafolat', models.CharField(blank=True, max_length=350, verbose_name='Kafolat')),
            ],
            options={
                'verbose_name': 'Product Max',
                'verbose_name_plural': 'Product Max',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Product_mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('product_name', models.CharField(max_length=350, null=True, verbose_name='Mahsulotning nomi')),
                ('description', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('olchov', models.CharField(blank=True, max_length=350, verbose_name='Olchovi')),
                ('budget', models.IntegerField(default=0, verbose_name='Budget')),
                ('price', models.CharField(choices=[('USD', 'DOLLARS'), ('UZS', 'SO`M')], default='USD', max_length=10, verbose_name='KURS')),
                ('material', models.CharField(blank=True, max_length=350, verbose_name='Material')),
                ('status', models.CharField(blank=True, max_length=350, verbose_name='Holati')),
                ('kafolat', models.CharField(blank=True, max_length=350, verbose_name='Kafolat')),
                ('category_code', models.CharField(max_length=20, verbose_name='Kategoriya kodi')),
                ('category_name', models.CharField(max_length=30, verbose_name='Kategoriya nomi')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Ost-kategoriya kodi')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-kategoriya nomi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Mini',
                'verbose_name_plural': 'Product Mini',
                'ordering': ['product_name'],
            },
        ),
    ]
